// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7iCXkC6beXO2brGockP_TzyeaAk56r-o',
    appId: '1:1053580752418:web:db21c41145bc7e1331fc7b',
    messagingSenderId: '1053580752418',
    projectId: 'ai-mood-2d7d0',
    authDomain: 'ai-mood-2d7d0.firebaseapp.com',
    storageBucket: 'ai-mood-2d7d0.firebasestorage.app',
    measurementId: 'G-H6ZHX6YJ3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL8HbbchxRU8n3qBh3pwZC7nKspq_XWA0',
    appId: '1:1053580752418:android:7b716f642c6d34c831fc7b',
    messagingSenderId: '1053580752418',
    projectId: 'ai-mood-2d7d0',
    storageBucket: 'ai-mood-2d7d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFBhoKxpFaLFvqcNDubLuTWlSL9VAZ8xg',
    appId: '1:1053580752418:ios:840bedc234e6fb1831fc7b',
    messagingSenderId: '1053580752418',
    projectId: 'ai-mood-2d7d0',
    storageBucket: 'ai-mood-2d7d0.firebasestorage.app',
    androidClientId:
        '1053580752418-vdggjepn4tv5chtnchaiss6ckmjgd8f1.apps.googleusercontent.com',
    iosClientId:
        '1053580752418-m6e1rta8a06p94sld2geedpvjb13vgdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiMood',
  );
}
